# Base URL and Browser(Currently - CHROME)
baseUrl: https://qa-publisher-portal.rmp.rakuten.com
browser: chrome

# WebDriver Settings
pageLoadStrategy: normal
browserSize: 1920x1000
holdBrowserOpen: false
reopenBrowserOnFail: true
screenshots: true
headless: false
downloadsFolder: build/downloads/csv/

#Proxy enabling
enableProxy: false

# Selenide Explicit wait
timeout: 10000