# Base URL and Browser(Currently - CHROME)
baseUrlAPI: https://qa-s-api.rmp.rakuten.com
baseUrl: https://qa-publisher-portal.rmp.rakuten.com
browser: chrome

# WebDriver Settings
pageLoadStrategy: normal
browserSize: 1920x1000
holdBrowserOpen: false
reopenBrowserOnFail: true
screenshots: true
headless: false

#Proxy enabling
enableProxy: false

# Selenide Explicit wait
timeout: 5000

##Sun May 10 15:47:41 IST 2020

#password=Passwd22
#DBNAME=rssp
#DBUSERNAME=Chandra
#DBHOST=35.245.192.83\:3306
#username=zafar.zafar@rakuten.com